#!/usr/bin/env bash
# setup.sh — Project N.O.M.A.D. Synology Setup Script
# This script prepares your Synology NAS to run Project N.O.M.A.D.

set -e

NOMAD_DIR="/volume1/docker/project-nomad"
ENV_FILE="${NOMAD_DIR}/.env"
COMPOSE_FILE="${NOMAD_DIR}/docker-compose.yml"

# ─── Colour helpers ───────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Colour

info()    { echo -e "${CYAN}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC}   $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║     Project N.O.M.A.D. — Synology Setup Script      ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════════════╝${NC}"
echo ""

# ─── 1. Verify Synology environment ───────────────────────────────────────────
info "Checking environment..."
if [ ! -d "/volume1" ]; then
  warn "/volume1 not found. This script is designed for Synology NAS."
  read -r -p "Continue anyway? [y/N] " CONTINUE
  [[ "$CONTINUE" =~ ^[Yy]$ ]] || error "Aborted."
else
  success "Synology /volume1 detected."
fi

# ─── 2. Create required directories ───────────────────────────────────────────
info "Creating directories under ${NOMAD_DIR}..."
mkdir -p \
  "${NOMAD_DIR}/storage" \
  "${NOMAD_DIR}/mysql" \
  "${NOMAD_DIR}/redis"
success "Directories created."

# ─── 3. Check if .env already exists ──────────────────────────────────────────
if [ -f "${ENV_FILE}" ]; then
  warn ".env file already exists at ${ENV_FILE}"
  warn "Skipping .env generation to avoid overwriting your existing configuration."
  echo ""
  echo -e "${BOLD}To start the stack:${NC}"
  echo "  cd ${NOMAD_DIR}"
  echo "  docker compose up -d"
  exit 0
fi

# ─── 4. Generate secrets ──────────────────────────────────────────────────────
info "Generating secrets..."
APP_KEY=$(openssl rand -hex 32)
MYSQL_ROOT_PASSWORD=$(openssl rand -hex 32)
MYSQL_PASSWORD=$(openssl rand -hex 32)
success "Secrets generated."

# ─── 5. Prompt for NAS IP ─────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}What is your NAS IP address?${NC}"
echo "  (e.g. 192.168.1.100 — this is what you use to access DSM)"
read -r -p "NAS IP: " NAS_IP

if [ -z "${NAS_IP}" ]; then
  warn "No IP entered — using placeholder '192.168.1.x'. Edit .env before starting."
  NAS_IP="192.168.1.x"
fi

# ─── 6. Write .env file ───────────────────────────────────────────────────────
info "Writing ${ENV_FILE}..."
cat > "${ENV_FILE}" <<EOF
# Project N.O.M.A.D. — Synology configuration
# Generated by setup.sh on $(date)

# ─── Admin URL ────────────────────────────────────────────────────────────────
URL=http://${NAS_IP}:8888

# ─── Secrets ──────────────────────────────────────────────────────────────────
APP_KEY=${APP_KEY}
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
MYSQL_PASSWORD=${MYSQL_PASSWORD}

# ─── Database ─────────────────────────────────────────────────────────────────
MYSQL_DATABASE=nomad
MYSQL_USER=nomad_user

# ─── Optional ─────────────────────────────────────────────────────────────────
LOG_LEVEL=info
EOF
chmod 600 "${ENV_FILE}"
success ".env file written (permissions: 600)."

# ─── 7. Copy docker-compose.yml if not present ────────────────────────────────
if [ ! -f "${COMPOSE_FILE}" ]; then
  info "Downloading docker-compose.yml..."
  if command -v curl &>/dev/null; then
    curl -fsSL "https://raw.githubusercontent.com/eizus/project-nomad-synology/main/docker-compose.yml" \
      -o "${COMPOSE_FILE}"
    success "docker-compose.yml downloaded."
  else
    warn "curl not found — please manually copy docker-compose.yml to ${NOMAD_DIR}/"
  fi
else
  info "docker-compose.yml already present, skipping download."
fi

# ─── 8. Done ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}Setup complete!${NC}"
echo ""
echo -e "${BOLD}Next steps:${NC}"
echo "  1. Review your config: nano ${ENV_FILE}"
echo "  2. Start the stack:"
echo "       cd ${NOMAD_DIR}"
echo "       docker compose up -d"
echo ""
echo -e "${BOLD}Once running, open:${NC}"
echo "  Admin UI → http://${NAS_IP}:8888"
echo "  Dozzle   → http://${NAS_IP}:9999"
echo ""
